spring.application.name=lets-play
spring.data.mongodb.uri=mongodb://localhost:27017/crud_assignment_db
jwt.secret=3zZ1jPzcVPk3nsi2J2utYviA4ntupskJ

Création du certificat HTTPS
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/letsplay.p12
server.ssl.key-store-password=Zone01pc
server.ssl.key-alias=letsplay
server.ssl.enabled=true

# trust.store=classpath:keystore/letsplay.p12
# trust.store.password=Zone01pc